version: '2.3'

services:
  app:
    runtime: nvidia
    build: .
    shm_size: '8gb'
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./:/workdir
    working_dir: /workdir
    ports:
      - "8888:8888"
      - "10022:22"
    tty: true